#!/bin/bash

dropcommand="DROP TABLE"
export PGPASSWORD=nono
error=false

if [ ! -e temptables ]; then
	exit 0;
fi

while read table; do
	echo "$dropcommand $table;"
	echo "$dropcommand $table;" | psql -U dns_monitor -h 127.0.0.1 || error=true
done < temptables

if [ ! $error ]; then
	rm temptables
fi
