#!/bin/bash

# Régi fájlok törlése
for f in `find /home/sutda/DNSmezzo/dump2/ -mtime +4 -type f`; do
	rm $f
done

# Elmúlt 24 óra fájljainak adatbázisba mentése
for f in `find /home/sutda/DNSmezzo/dump2/ -mtime -1 -type f`; do
	home/sutda/DNSmezzo/packets2postgresql  -v -c 'host=127.0.0.1 user=dns_monitor password=nono' /home/sutda/DNSmezzo/dump2/ns1.puff2.Oct211851.cap$f
done

# Új jelentések gyártása
cd /home/sutda/DNSmezzo/reporting/sajat;
make clean
time make
chown sutda:sutda *
make install


